on:
  push:
    branches: master

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      - uses: actions/cache@v2
        with:
          path: .venv
          key: poetry-${{ hashFiles('poetry.lock') }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.6.1 python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
      - name: Verify Poetry installation
        run: poetry --version
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config installer.parallel false
      - name: Debugging information
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -al
          echo "Poetry environment info:"
          poetry env info
      - name: Install dependencies
        run: |
          poetry install -vv
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project pyquil \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --testbed ci-runner-linux \
          --err \
          --file results.json \ 
          poetry run pytest --benchmark-json results.json test/benchmarks 
